version: ~> 1.0

language: scala

scala:
  - 2.12.10
  - 2.13.1

git:
  depth: false # Avoid sbt-dynver not seeing the tag

env:
  - TRAVIS_JDK=8
  - TRAVIS_JDK=11

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version

script:
   - sbt ++$TRAVIS_SCALA_VERSION test mimaReportBinaryIssues
   # Test sample applications
   - sbt ++$TRAVIS_SCALA_VERSION publishLocal "print play-mailer/version" | tee /tmp/out.txt
   - export PLAY_MAILER_VERSION=`tail -1 /tmp/out`
   - pushd samples/compile-timeDI/ && sbt ++$TRAVIS_SCALA_VERSION test && popd
   - pushd samples/runtimeDI/ && sbt ++$TRAVIS_SCALA_VERSION test && popd

jobs:
  include:
    - stage: deploy
      name: "TEMP Publish artifacts to Bintray"
      script: sbt +mimaReportBinaryIssues
      scala: 2.13.1
      env: TRAVIS_JDK=11

stages:
  - name: test
  - name: publish
#    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

cache:
  directories:
    - $HOME/.coursier/cache
    - $HOME/.ivy2
    - $HOME/.jabba/jdk
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
